Seqkit
nf-core/seqinspector pull request #59
Opened 2024-10-29 14:53 UTC by sarahjeeeze

Add seqkit stats nf-core module 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/seqinspector/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/seqinspector _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2024-10-29 18:02 UTC, MatthiasZepper requested changes
Thank you for your contribution!

Ultimately, the pipeline will allow to flexibly choose the tools that are run, so having more tools in the pipeline is always great, but what exactly was your rationale here?

Admittedly, I just skimmed over the description, but to me, it seems that it is predominantly meant to run on FASTA files and for judging the quality of genome assemblies. Unless I missed some relevant arguments, its application on sequencing reads is in my opinion does not really yield too many meaningful statistics - at least for Illumina, for Nanopore probably yes. 

Do you happen to have a Nanopore example? For Illumina, this is basically all you get:
```
file	format	type	num_seqs	sum_len	min_len	avg_len	max_len
S11_L001_R1_001.fastq.gz	FASTQ	DNA	35875355	5417178605	151	151.0	151
S11_L001_R1_001.fastq.gz	FASTQ	DNA	35875355	322878195	9	9.0	9
S11_L001_R2_001.fastq.gz	FASTQ	DNA	35875355	5417178605	151	151.0	151
```

But with regard to the code, this already looks very good and tidy!

I am only missing a `publishDir` directive in the config, so that the reports from the stats output channel are published in a subfolder of the `outdir`.

2024-10-30 09:47 UTC, sarahjeeeze commented on conf/modules.config
> +        ext.args = ''
yeah it is defined here - I guess you would only overwrite it if you dont want your output published in the standard way.

https://github.com/nf-core/seqinspector/blob/9cd232c89429d4fb404b5859f77b9724558e653a/conf/modules.config#L15

2024-10-30 09:47 UTC, sarahjeeeze commented on workflows/seqinspector.nf
> +    SEQKIT_STATS (
yeah am outputting them

2024-10-30 09:53 UTC, sarahjeeeze commented on docs/output.md
> +- `seqkit/`
see above

2024-10-30 10:13 UTC, sarahjeeeze commented on docs/output.md
> +[SeqkitStats](https://bioinf.shenwei.me/seqkit/usage/#stats) it gives general quality metrics about your sequenced reads including average read lengths, GC(%) and n50's. For further reading and docum
Updated text a little, should i specifically mention this is more useful for nanopore data?  for ilumina etc you do still get n50's etc 

```
file	format	type	num_seqs	sum_len	min_len	avg_len	max_len	Q1	Q2	Q3	sum_gap	N50	N50_num	Q20(%)	Q30(%)	AvgQual	GC(%)
sample1_R1.fastq.gz	FASTQ	DNA	1377513	411872902	35	299.0	301	300.0	301.0	301.0	0	301	1	99.10	97.54	29.31	38.53
sample1_R2.fastq.gz	FASTQ	DNA	1377513	411840994	35	299.0	301	300.0	301.0	301.0	0	301	1	97.11	93.54	25.78	38.54
```

2024-10-30 10:28 UTC, MatthiasZepper commented on conf/modules.config
> +        ext.args = ''
Oooh fancy - a central `publishDir` directive for all modules ?!? That's smart and has totally escaped me...sorry then for the false accusations!

2024-10-30 10:29 UTC, MatthiasZepper approved these changes

2026-06-12 12:35 UTC, MatthiasZepper commented on modules/nf-core/seqkit/stats/main.nf
> +        ? 'https://depot.galaxyproject.org/singularity/seqkit:2.9.0--h9ee0642_0'
Is it OK, when the module is not yet migrated to Seqera Containers?

2026-06-12 13:27 UTC, MatthiasZepper approved these changes
Looks good to me. A few minor remarks, but ultimately it is a question for the user which tools they want to run,

2026-06-12 13:27 UTC, MatthiasZepper commented on subworkflows/local/utils_nfcore_seqinspector_pipeline/main.nf
> +        tools_list << 'seqkit_stats'
Do we really need Seqfu and Seqkit stats? I know it is hard to decide which to favor as default, but I believe both compute essentially the same.

2026-06-12 13:27 UTC, MatthiasZepper commented on conf/modules.config
> +        ext.args = ''
Seqkit stats has a `--tabular` / `-T` parameter that makes t[he output easier to process for machines](https://bioinf.shenwei.me/seqkit/usage/#stats). However, if MultiQC can handle the default output nicely, I guess we can skip it.

2026-06-12 15:06 UTC, maxulysse commented on conf/modules.config
> +        ext.args = ''
MultiQC can handle it

2026-06-12 15:12 UTC, maxulysse commented on subworkflows/local/utils_nfcore_seqinspector_pipeline/main.nf
> +        tools_list << 'seqkit_stats'
Good point...
I am choosing for now in term of popularity, and I will assess further with the boss lady:

https://github.com/shenwei356/seqkit
https://github.com/telatin/seqfu2

2026-06-15 10:09 UTC, maxulysse commented on modules/nf-core/seqkit/stats/main.nf
> +        ? 'https://depot.galaxyproject.org/singularity/seqkit:2.9.0--h9ee0642_0'
Fixed

2026-06-15 10:27 UTC, merged